spring:
  application:
    name: admin-server
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
   register-with-eureka: true
   fetch-registry: false

server:
   port: 1111 