server:
  port: 8888

spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tesfu-hab/configuration_properties.git  # Replace with your GitHub repo URL
          default-label: main
          clone-on-start: true

  profiles:
   active: git  # Use Git as the config source
  boot:
    admin:
      client:
        url: http://localhost:1111
        auto-registration: true
        instance:
          name: CONFIG-SERVER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

